title: Sai Sandeep Naraparaju
logo: /assets/img/sandeep2.jpg
description: Linkedin-[naraparajusaisandeep](https://www.linkedin.com/in/naraparajusaisandeep/) | Medium-[saisandeep_10624](https://medium.com/@saisandeep_10624)
show_downloads: false
theme: jekyll-theme-minimal
