title: Sai Sandeep Naraparaju
logo: /assets/img/sandeep2.jpg
description: 5 years of experience in delivering data-intensive, scalable analytical solutions across diverse industries. Proficient in Python, Predictive Modelling, NLP, Forecasting, Data Processing, Cloud Technologies, Data Analysis, and Dashboard Visualizations.
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
