title: Sai Sandeep Naraparaju
logo: /assets/img/sandeep2.jpg
description: 5 years of experience in delivering data-intensive, scalable analytical solutions across diverse industries. Proficient in Python, Predictive Modelling, NLP, Forecasting, Data Processing, Cloud Technologies, Data Analysis, and Dashboard Visualizations.
show_downloads: false
theme: jekyll-theme-minimal
